services:
  - type: web
    name: sistema-casos-comunitarios
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-casos-db
          property: connectionString
    database:
      name: sistema-casos-db
      plan: free

databases:
  - name: sistema-casos-db
    plan: free