# Generated by Django 5.2.5 on 2025-09-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Imagen de encabezado')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Texto del pie de página')),
                ('primary_color', models.CharField(default='#0057B7', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#FFD700', max_length=7, verbose_name='Color secundario')),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('DELETED', 'Eliminado')], max_length=10, verbose_name='Acción')),
                ('case_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Caso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('en_tramite', 'En trámite'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='registrado', max_length=20, verbose_name='Estado')),
                ('location_blocks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bloque(s) donde ocurre el conflicto')),
                ('other_location_block', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro bloque')),
                ('resolution_method', models.CharField(blank=True, max_length=500, null=True, verbose_name='Medio(s) de resolución')),
                ('other_resolution_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro medio de resolución')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de caso')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='Nombre del solicitante')),
                ('applicant_id', models.CharField(max_length=20, verbose_name='Cédula del solicitante')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del solicitante')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del solicitante')),
                ('involved_name', models.CharField(max_length=100, verbose_name='Nombre del involucrado')),
                ('involved_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del involucrado')),
                ('conflict_description', models.TextField(verbose_name='Descripción del conflicto')),
                ('location', models.CharField(max_length=200, verbose_name='Lugar del conflicto')),
                ('conflict_type', models.CharField(choices=[('vecinal', 'Vecinal'), ('individual', 'Individual'), ('comunitario', 'Comunitario'), ('contravencion', 'Contravención sin privación de libertad'), ('patrimonial', 'Obligaciones patrimoniales hasta cinco salarios básicos'), ('otro', 'Otro')], default='vecinal', max_length=50, verbose_name='Tipo de conflicto')),
                ('other_conflict_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro tipo de conflicto')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor aproximado (patrimonial)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales')),
                ('extension_granted', models.BooleanField(default=False, verbose_name='Prórroga concedida')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_judge', to=settings.AUTH_USER_MODEL, verbose_name='Juez asignado')),
            ],
            options={
                'verbose_name': 'Caso Comunitario',
                'verbose_name_plural': 'Casos Comunitarios',
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombres completos')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('role_request', models.CharField(choices=[('juez', 'Juez de Paz'), ('admin', 'Administrador')], max_length=10, verbose_name='Rol a solicitar')),
                ('approved_by_admin', models.BooleanField(default=False, verbose_name='Aprobado por Admin')),
                ('role', models.CharField(blank=True, choices=[('juez', 'Juez de Paz'), ('admin', 'Administrador')], max_length=10, null=True, verbose_name='Rol asignado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
