# Generated by Django 5.2.5 on 2025-08-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='resolution_method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medio de resolución'),
        ),
    ]
