# Generated by Django 5.2.5 on 2025-08-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_case_resolution_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Imagen de encabezado')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Texto del pie de página')),
                ('primary_color', models.CharField(default='#0057B7', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#FFD700', max_length=7, verbose_name='Color secundario')),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
            },
        ),
    ]
