# Generated by Django 5.2.5 on 2025-08-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='conflict_type',
            field=models.CharField(choices=[('vecinal', 'Vecinal'), ('individual', 'Individual'), ('comunitario', 'Comunitario'), ('contravencion', 'Contravención sin privación de libertad'), ('patrimonial', 'Obligaciones patrimoniales hasta cinco salarios básicos'), ('otro', 'Otro')], default='vecinal', max_length=50, verbose_name='Tipo de conflicto'),
        ),
    ]
