# Generated by Django 5.2.5 on 2025-08-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_case_conflict_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='location_blocks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bloque(s) donde ocurre el conflicto'),
        ),
        migrations.AddField(
            model_name='case',
            name='other_location_block',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro bloque'),
        ),
    ]
