# Generated by Django 5.2.5 on 2025-09-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_case_location_blocks_case_other_location_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('en_tramite', 'En trámite'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='registrado', max_length=20, verbose_name='Estado'),
        ),
    ]
